import * as dotenv from 'dotenv';

dotenv.config();

const {
  PORT,
  NODE_ENV,
  CLIENT_URL,

  MONGODB_URI,

  ACCESS_SECRET,
  ACCESS_EXPIRE_IN,
  REFRESH_SECRET,
  REFRESH_EXPIRE_IN,
  MAIL_SECRET,
  MAIL_EXPIRE_IN,

  SENDGRID_API_KEY,
  MAIL_SENDER,
  TEMPLATE_PATH,
} = process.env;

export const GENERAL_CONFIG = {
  PORT: parseInt(PORT),
  NODE_ENV,
  CLIENT_URL,
};

export const DATABASE_CONFIG = { MONGODB_URI };

export const JWT_CONFIG = {
  ACCESS_SECRET,
  ACCESS_EXPIRE_IN,
  REFRESH_SECRET,
  REFRESH_EXPIRE_IN,
  MAIL_SECRET,
  MAIL_EXPIRE_IN,
};

export const MAIL_CONFIG = {
  API_KEY: SENDGRID_API_KEY,
  SENDER: MAIL_SENDER,
  TEMPLATE_PATH,
};
