export enum ErrorCode {
  // Auth / User
  USER_EXISTED = 'USER_EXISTED',

  // Mail
  SEND_EMAIL_FAILED = 'SEND_EMAIL_FAILED',
  LOAD_TEMPLATE_FAILED = 'LOAD_TEMPLATE_FAILED',
  RENDER_TEMPLATE_FAILED = 'RENDER_TEMPLATE_FAILED',
}
